---
# tasks file for vitalied.user

- name: add user
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_comment: "{{ user_name }}"
  tags: vitalied.user

- name: set up authorized_keys for the user
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  ignore_errors: yes
  tags: vitalied.user
